### ISSUE TITLE
cannot start WSO2 IoT using docker compose

### ISSUE THREAD

**Issue by lanphan** [wso2/docker-iot#11]
**Description:**
I get the latest code today (Mar 31), build docker images locally then run docker-compose. Got issue below:

wso2iot-analytics    | [2018-03-31 14:39:35,765] [IoT-Analytics] ERROR {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Keymanager is unreachable, Waiting....

1 thing strange that, around 1 or 2 weeks ago, when version of images is still 3.1.0, I download it and run it successfully (build and update to use 3.2.0)

**Affected Product Version:**
3.2.0

**OS, DB, other environment details and versions:**    
Ubuntu 17.10
Docker version 17.12.0-ce, build c97c6d6
docker info
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 74
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-16-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.793GiB
Name: vultr.guest
ID: XS4M:7NDR:7ISS:YUMR:NSYA:EUJ7:SP7F:NXD5:AM26:Q5EW:EL5V:3XMZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

docker-compose version 1.18.0, build 8dd22a9

**Steps to reproduce:**
1/ Clone this repo
2/ Go to dockerfiles/base, following instructions to download jdk, mysql connector and wso2 iot
3/ Unpack jdk and wso2 iot
4/ build image base, analytics, broker and iot server
5/ update docker-compose.yml (using image name just built in step above)
6/ docker-compose up 
7/ Got my problem

**Related Issues:**

**Comment by lanphan** [comment]
Please note that I already tried to use tag v3.2.0.1, but still got the same problem.

**Comment by ctienshi** [comment]
@lanphan This is a known issue, which is reported earlier in "wso2/product-iots".
Please refer to https://github.com/wso2/product-iots/issues/1158.

**Comment by lanphan** [comment]
@ctienshi I don't find any relevant here ... I run docker compose of WSO2 IoT in a fresh environment (no other docker container running, no port conflict), then I got issue about KeyManager in wso2iot-analytics cannot be reached ...
Today, I get latest code and upgrade to IoT version 3.3.0, but still got this error, I don't know how do you guys run this compose? Can you share some experience?

Thanks.

**Comment by lanphan** [comment]
@ctienshi Thanks for your sharing. Can you share me the time which keymanager in Iot Server requires to init? I'm running this under VPS with 6GB RAM, and wait for it for a long time (around half of hour), but still got that error ...

Some questions:
1/ why we don't update info of keymanager in Analytics container to point to IoT Server container directly?
2/ Is there any way for me to debug why keymanager is not reachable?

Thanks.

**Comment by VimukthiPerera** [comment]
We can close this because we no longer maintain docker resources for IoT server
