### ISSUE TITLE
jdk version in readme out of date

### ISSUE THREAD

**Issue by mnort** [wso2/docker-iot#2]
current build.sh appears to look for jdk 8, readme still has 7

```
Provisioning Method: default
A valid JDK distribution was not found at /Users/mnort/projects/docker-iot/dockerfile/common/provision/default/files folder. Expected: jdk-8u112-linux-x64.tar.gz
Cleaning...
```

**Comment by DilanUA** [comment]
Thanks for your interest in testing out the product. However, we are closing this issue now since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
