### ISSUE TITLE
500 Error after login

### ISSUE THREAD

**Issue by lebowski42** [wso2/docker-iot#21]
**Description:**
After login get "Error 500 Something went wrong and we're trying to fix it."

**Affected Product Version:**
3.3.0

**OS, DB, other environment details and versions:**    
ubuntu 16.04

**Steps to reproduce:**
Build the docker image, running change-ip.sh and change localhost to hostname (access from internet)

**Related Issues:**
I build an docker-image as described in the README. After starting the three containers i logged in into the iot-server container and executed change-ip.sh. I changed localhost to _mdm.replaced.de_  (replaced.de isn't the real hostname, i changed it for this thread)

After restarting the three container in the described order, i navigate to _https://mdm.replaced.de:9443_ and i could login. After this  got the page "Error 500
Something went wrong and we're trying to fix it."

I attached the interesting parts of the wso2-esb-errors.log
[wso2-esb-errors.log](https://github.com/wso2/docker-iot/files/1968417/wso2-esb-errors.log)

**Comment by VimukthiPerera** [comment]
We can close this because we no longer maintain docker resources for IoT server
