### ISSUE TITLE
WSO IoT Server - Device Manager UI give HTTP error 405

### ISSUE THREAD

**Issue by SreenivasAngara** [wso2/docker-iot#22]
**Description:**
Trying to run WSO2 IoT Server docker image. Able to connect to Admin console. Cannot connect Device management console and receive HTTP 405 error code.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 IoT Server version 3.3.0

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:** 
docker run -it -p 9443:9443 docker.wso2.com/wso2iot-server
https://localhost:9443/carbon/admin/index.jsp?loginStatus=true ( works fine)
https://localhost:9443/devicemgmt ( This url return 405 error)

**Related Issues:**

**Comment by VimukthiPerera** [comment]
We can close this because we no longer maintain docker resources for IoT server
